[BI-12] global search
BinarCode/blog-intership pull request #28
Opened 2021-08-25 10:47 UTC by Lucian2

Am folosit Vue Suggestion pentru global search.

![image](https://user-images.githubusercontent.com/62387210/130777464-2505d775-7ba5-47be-acef-a430bb7f58a1.png)

2021-09-01 10:01 UTC, PascuMihai commented on src/api/blogService.js
> +  let params = {
```jsx
let params = {
    page,
    perPage,
    sort,
  };
```
you can use the shorhand

2021-09-01 10:02 UTC, PascuMihai commented on src/api/blogService.js
> +      '/api/restify/blogs?sort=-views&search=' + searchTerm,
you have the sort query in the params object and also search can go there also

2021-09-01 10:03 UTC, PascuMihai commented on src/api/blogService.js
> +      '/api/restify/blogs?sort=-views&search=' + searchTerm,
And the seach endpoint is different {{api}}/api/blogs/advance-search?search=Prof

2021-09-01 10:04 UTC, PascuMihai commented on src/api/blogService.js
> +export async function getBlogSearchResults(searchTerm) {
if we have search here why do we use search in the above function?

2021-09-01 10:06 UTC, PascuMihai commented on src/components/Tiptap/TiptapMenuBar.vue
> -        :action="() => editor.chain().focus().toggleBold().run()"
not sure why we have this changes here, this should focus on search not on tip tap

2021-09-01 10:31 UTC, PascuMihai commented on src/components/BaseNavbar.vue
> +              :controls="{
let's add this object into a computed

2021-09-02 06:44 UTC, PascuMihai approved these changes

2021-09-02 06:45 UTC, PascuMihai requested changes
There are some errois in the console
![image](https://user-images.githubusercontent.com/54642532/131795580-0624c527-3685-4adb-b154-71547190e634.png)

2021-09-03 11:43 UTC, PascuMihai approved these changes

2021-09-03 13:44 UTC, Ceciliaa approved these changes

2021-09-03 13:59 UTC, merged